name: ci
on:
  pull_request:
  workflow_dispatch:

jobs:
  application-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: application-ci
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: restore node modules cache
        id: restore-node-modules-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/bun.lock') }}
      - run: bun install --frozen-lockfile
      - run: bun knip-bun
      - run: task cloudflare-type-generate
      - name: diff check cloudflare-type-generate
        run: git diff --exit-code -- worker-configuration.d.ts
      - run: bun run tsc --noEmit
      - run: bunx biome lint
      - run: bunx biome format
      - run: bun editorconfig-checker

      - name: Run Migrations
        env:
          DB_URL: postgresql://postgres:postgres@127.0.0.1:5433/postgres
          MIGRATION_DIR: supabase/migrations
        run: |
          bun script/database/migrate.ts ${{ env.DB_URL }} ${{ env.MIGRATION_DIR }}
      - run: bun vitest run

  supabase-change-detection:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: supabase-change-detection
    outputs:
      is-changed: ${{ steps.supabase-change-detection.outputs.supabase }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: supabase-change-detection
        with:
          filters: |
            supabase:
              - 'supabase/**'

  supabase-ci:
    needs: supabase-change-detection
    if: needs.supabase-change-detection.outputs.is-changed == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: supabase-ci
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}
      - run: supabase db start
      - run: supabase db lint
      - run: supabase test db
      - run: supabase db push --dry-run
